*** Settings ***
Documentation    TDD test data templates for all entity API endpoints
Resource         common.robot

*** Variables ***
# Test data templates for all entities
&{PATIENT_TEMPLATE}      first_name=TestPatient    last_name=TDD    birthdate=1990-01-01    sex=male    contact_number=+1234567890    country_id=1
&{THERAPIST_TEMPLATE}    first_name=TestTherapist    last_name=TDD    age=30    bio=TDD test therapist bio    clinic_id=1    picture=https://example.com/test.jpg    specialization=Physical Therapy    contact_number=+0987654321    email=therapist@tdd.com    country_id=1
&{REPORT_TEMPLATE}       title=TDD Test Report    description=Test report for TDD implementation    type_id=1    language_id=1    patient_id=    therapist_id=    content={"diagnosis": "TDD test", "treatment": "test implementation", "notes": "Generated by Robot Framework TDD"}

# ReadParameters for testing search/filter functionality
&{READ_PARAMETERS}       search=    limit=10    offset=0    sort_by=created_at    sort_order=desc